---
title: "R Notebook"
output:
  word_document: default
  html_notebook: default
---

```{r}
tests.df <- read.csv('./tests.csv')
cassandra.tests.df <- tests.df[tests.df$database == "cassandra", ]
mongo.tests.df <- tests.df[tests.df$database == "mongodb", ]
neo4j.tests.df <- tests.df[tests.df$database == "neo4j", ]

mongo.read.only.df <- mongo.tests.df[mongo.tests.df$test_type == 'read_only', ]
cassandra.read.only.df <- cassandra.tests.df[cassandra.tests.df$test_type == 'read_only', ]
neo4j.read.only.df <- neo4j.tests.df[neo4j.tests.df$test_type == 'read_only', ]
mongo.mixed.df <- mongo.tests.df[mongo.tests.df$test_type == 'mixed', ]
cassandra.mixed.df <- cassandra.tests.df[cassandra.tests.df$test_type == 'mixed', ]
neo4j.mixed.df <- neo4j.tests.df[neo4j.tests.df$test_type == 'mixed', ]

# Convenience variable for analysis
numeric.cols <- c('aggregateSpendRun', 'birthdayRun', 'ordersByRangeRun', 'popularityRun', 'recEngineRun')
```

### Aggregate summary statistics

Table in the main report:
```{r}
get.means.col <- function(which.col) {
  return(c(
    mean(tests.df[, which.col]),
    mean(mongo.tests.df[, which.col]),
    mean(mongo.read.only.df[, which.col]),
    mean(mongo.mixed.df[, which.col]),
    mean(cassandra.tests.df[, which.col]),
    mean(cassandra.read.only.df[, which.col]),
    mean(cassandra.mixed.df[, which.col]),
    mean(neo4j.tests.df[, which.col]),
    mean(neo4j.read.only.df[, which.col]),
    mean(neo4j.mixed.df[, which.col])
  ))
}

get.sd.col <- function(which.col) {
  return(c(
    sd(tests.df[, which.col]),
    sd(mongo.tests.df[, which.col]),
    sd(mongo.read.only.df[, which.col]),
    sd(mongo.mixed.df[, which.col]),
    sd(cassandra.tests.df[, which.col]),
    sd(cassandra.read.only.df[, which.col]),
    sd(cassandra.mixed.df[, which.col]),
    sd(neo4j.tests.df[, which.col]),
    sd(neo4j.read.only.df[, which.col]),
    sd(neo4j.mixed.df[, which.col])
  ))
}

db.and.class.col <- c(
  "All",
  "MongoDB (Aggregate)",
  "MongoDB (Read-only)",
  "MongoDB (Mixed)",
  "C* (Aggregate)",
  "C* (Read-only)",
  "C* (Mixed)",
  "Neo4j (Aggregate)",
  "Neo4j (Read-only)",
  "Neo4j (Mixed)"
)

means.df <- data.frame(
  'DB and Class'=db.and.class.col,
   'aggregateSpendRun'=get.means.col('aggregateSpendRun'),
   'birthdayRun'=get.means.col('birthdayRun'),
   'ordersByRangeRun'=get.means.col('ordersByRangeRun'),
   'popularityRun'=get.means.col('popularityRun'),
   'recEngineRun'=get.means.col('recEngineRun')
)
sd.df <- data.frame(
  'DB and Class'=db.and.class.col,
   'aggregateSpendRun'=get.sd.col('aggregateSpendRun'),
   'birthdayRun'=get.sd.col('birthdayRun'),
   'ordersByRangeRun'=get.sd.col('ordersByRangeRun'),
   'popularityRun'=get.sd.col('popularityRun'),
   'recEngineRun'=get.sd.col('recEngineRun')
)
```

```{r}
means.df
```

```{r}
sd.df
```


```{r}
# write.csv(means.df, file="means.csv")
# write.csv(sd.df, file="stddevs.csv")
```


```{r}
summary(tests.df)
```

```{r}
summary(cassandra.tests.df)
```



```{r}
summary(neo4j.tests.df)
```

Some helper methods:
```{r}
get.summary.statistics <- function(df, which.Db) {
  print(sprintf("Printing Summary Statistics for %s", which.Db))
  print("Aggregate")
  aggregate.summary <- summary(df)
  write.csv(as.matrix(aggregate.summary), sprintf("%s_aggregate.csv", which.Db))
  print(aggregate.summary)
  print("Read-only")
  read.summary <- summary(df[df$test_type == 'read_only', ])
  write.csv(as.matrix(read.summary), sprintf("%s_read.csv", which.Db))
  print(read.summary)
  print("Mixed")
  mixed.summary <- summary(df[df$test_type=='mixed', ])
  write.csv(as.matrix(mixed.summary), sprintf("%s_mixed.csv", which.Db))
  print(mixed.summary)
}
```

```{r}
get.bar.plots.for.tests <- function(df, which.Db) {
  read.only.df <- df[df$test_type == 'read_only', ]
  mixed.df <- df[df$test_type=='mixed', ]
  par(mfrow=c(2,3))
  for (i in 1:5) {
    read.means <- mean(read.only.df[, numeric.cols[i]])
    mixed.means <- mean(mixed.df[, numeric.cols[i]])
    barplot(c(read.means, mixed.means), names.arg=c("read", "mixed"), main=sprintf("%s: %s", which.Db, numeric.cols[i]))
  }
}
```



### MongoDB
```{r}
get.summary.statistics(mongo.tests.df, "MongoDB")

```

```{r}
get.bar.plots.for.tests(mongo.tests.df, "MongoDB")
```

### Neo4j
```{r}
get.summary.statistics(neo4j.tests.df, "Neo4j")
```

```{r}
get.bar.plots.for.tests(neo4j.tests.df, "Neo4j")
```

### Cassandra
```{r}
cassandra.tests.df$recEngineRun <- 0 # Set this to zero, just so our methods don't blow up on us.
get.summary.statistics(cassandra.tests.df, "Cassandra")
```

```{r}
get.bar.plots.for.tests(cassandra.tests.df, "Cassandra")
```

### Side-by-side comparisons
First, taking a look at reads: 
```{r}
par(mfrow=c(2,3))
for (i in 1:5) {
  mongo.read.means <- mean(mongo.read.only.df[, numeric.cols[i]])
  cassandra.read.means <- mean(cassandra.read.only.df[, numeric.cols[i]])
  neo4j.read.means <- mean(neo4j.read.only.df[, numeric.cols[i]])
  barplot(c(mongo.read.means,
            cassandra.read.means,
            neo4j.read.means),
          names.arg=c("MongoDB", "C*", "Neo4j"),
          main=sprintf("Read-only: %s", numeric.cols[i]))
}
```

```{r}
par(mfrow=c(2,3))
for (i in 1:5) {
  mongo.mixed.means <- mean(mongo.mixed.df[, numeric.cols[i]])
  cassandra.mixed.means <- mean(cassandra.mixed.df[, numeric.cols[i]])
  neo4j.mixed.means <- mean(neo4j.mixed.df[, numeric.cols[i]])
  barplot(c(mongo.mixed.means,
            cassandra.mixed.means,
            neo4j.mixed.means),
          names.arg=c("MongoDB", "C*", "Neo4j"),
          main=sprintf("Mixed: %s", numeric.cols[i]))
}
```
